[package]
name = "river"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "store_concurrency"
harness = false

[[bench]]
name = "store_ops"
harness = false

[[bench]]
name = "store_workloads"
harness = false

[[bench]]
name = "protocol"
harness = false

[[bench]]
name = "ttl_persistence"
harness = false
